- id: doi:10.1371/journal.pcbi.1007128
  image: https://github.com/almasudme/lab_website_test/blob/main/images/nshot.png
#  buttons:
#    - type: manubot
#      link: https://greenelab.github.io/meta-review/
#    - type: source
#      text: Manuscript Source
#      link: https://github.com/greenelab/meta-review
#    - type: website
#      link: http://manubot.org/
#  tags:
#    - open science
#    - collaboration
#  repo: https://github.com/ayeshasdina/FSProtoTransfer

- id: https://doi.org/10.32473/flairs.38.1.138858
  image: https://github.com/almasudme/lab_website_test/blob/main/images/fsproto.png

